spring:
  datasources:
    target:
      jdbc-url: jdbc:sqlserver://localhost:1434;databaseName=Linsce_Adq_br;encrypt=true;trustServerCertificate=true
      username: admin
      password: 8dqvFN920SErXLWz
      tabla: comercios_br
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      environment: server
    informix:
      origin:
        jdbc-url: jdbc:informix-sqli://172.29.40.29:1540/catalogo_pos
        username: bocontrov
        password: xHJ3%<8uU.=L/svbY
        tabla-origen: comercios_br
        driver-class-name: com.informix.jdbc.IfxDriver
        maximumPoolSize: 150
        minimumIdle: 2
        properties:
          cachePrepStmts: true
          prepStmtCacheSize: 256
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
      h2:
        poolName: h2MemoryDatabasePool
        driverClassName: org.h2.Driver
        jdbcUrl: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        maximumPoolSize: 150
        minimumIdle: 2
    batch:
      jdbc:
        initialize-schema: never
  params:
    chunk-size: 10000